<?php
$title = 'Cadastrar um nova Cidade';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->basePath('localizacao/cidade/add'));
$form->prepare();
?>
<div class="page-header">
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id'));?>
    <div class="form-group">
    	<label for="nome" class="col-sm-2 control-label">Nome</label>
    	<div class="col-sm-3">
    		<?php echo $this->formRow($form->get('nome')); ?>
    	</div>
    </div>
    <div class="form-group">
    	<label for="latitude" class="col-sm-2 control-label">Latitude</label>
    	<div class="col-sm-3">
    		<?php echo $this->formRow($form->get('latitude')); ?>
    	</div>
    </div>
    <div class="form-group">
    	<label for="longitude" class="col-sm-2 control-label">Longitude</label>
    	<div class="col-sm-3">
    		<?php echo $this->formRow($form->get('longitude')); ?>
    	</div>
    </div>
    <div class="form-group">
    	<div class="col-sm-offset-2 col-sm-4">
    		<?php echo $this->formSubmit($form->get('submit')); ?>
    	</div>
    </div>
<?php echo $this->form()->closeTag();?>
    <div class="row">
        <nav class="menu">
            <li><a href="/localizacao/cidade/list">Cidade List</a></li>
        </nav>
    </div>
</div>