<a href="usuario/add">
    Novo Usuário
</a>
<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Nome
        </th>
        <th>
            Idade
        </th>
        <th>
            Nome
        </th>
    </tr>
    <?php foreach ($usuarios as $usuario): ?>
    <tr>
        <td>
            <?php  echo $usuario->id; ?>
        </td>
        <td>
            <?php echo $usuario->nome; ?>
        </td>
        <td>
            <?php echo $usuario->idade; ?>
        </td>
        <td>
            <?php echo $usuario->perfil->nome; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>


